### ISSUE TITLE
Rebrand the app

### ISSUE THREAD

**Issue by opensource-assist** [seanbreckenridge/keepassxc-pwned#12]
- Choose a more generic name instead of 'keepassxc-pwned' so that it would be more relevant to support other password database types.
- Rename the repository to be in consistence with the new name.
- Design an icon for the app.

My inspirations for a new name are:
- openpasscheck
- PassFLASK
- passgone
- pass::shock

**Comment by purarue** [comment]
I don't really plan to expand this to other password managers, any password manager can choose to do something similar -- extract the database contents and send requests off to the PwnedPasswords API.

If someone wants to submit a PR to expand this to another local password manager, that'd be OK with me, and I'd consider changing the name then.

**Comment by opensource-assist** [comment]
@seanbreckenridge

> I don't really plan to expand this to other password managers, any password manager can choose to do something similar -- extract the database contents and send requests off to the PwnedPasswords API.
> 
> If someone wants to submit a PR to expand this to another local password manager, that'd be OK with me, and I'd consider changing the name then.

Very busy now, but I'll do that when I'd have the time.

**Comment by purarue** [comment]
Closing this for now, feel free to open a new issue/PR if anyone wants to add another database.
