### ISSUE TITLE
Not snap-compatible

### ISSUE THREAD

**Issue by Thomas131** [seanbreckenridge/keepassxc-pwned#15]
Hi!
At my Linux Mint 19.1 Maschine with keepassxc installed as a snap, it didn't work without manual patching ... replacing every keepassxc-cli to keepassxc.cli in keepass_wrapper.py did the job for me.

**Comment by purarue** [comment]
Ah.

I can add a flag which lets you change what the name of the `keepassxc-cli` binary is. Perhaps call it `--bin`?

edit: hmm, or `--keepassxc-cli` may make more sense.

**Comment by purarue** [comment]
Will probably change it to force you to instead specify the full path to binary.

**Comment by purarue** [comment]
Hey @Thomas131, I've pushed a fix to `add_keepass_flag`, could I get you to test this by doing:

```
pip3 uninstall -y keepassxc-pwned
pip3 install git+https://github.com/seanbreckenridge/keepassxc-pwned@add_keepass_flag
```

And specifying the location like:

`keepassxc_pwned --keepassxc-cli "$(which keepassxc.cli)" <DATABASE>`

If that works I'll merge into master and bump the version soon.

**Comment by Thomas131** [comment]
Thanks, works perfectly. (And it seems like my previous answer got lost, sorry)

**Comment by purarue** [comment]
Pushed version 0.3.1 to pypi.

You can uninstall keepassxc_pwned and re-install from there:

```
pip3 uninstall -y keepassxc-pwned
pip3 install -U keepassxc-pwned
```

Thanks for opening the issue!
