### ISSUE TITLE
Use the click library in the CLI

### ISSUE THREAD

**Issue by opensource-assist** [seanbreckenridge/keepassxc-pwned#9]
The Python [click](https://github.com/pallets/click) library is a very nice tool for a simplified creation of command-line interfaces.
Please look at the examples on their GitHub repo and you see how beautiful it is.

**Comment by purarue** [comment]
Yeah, I've used click in the past.

I didn't expect the argument count to grow to what it is now, I tend to use `argparse`/`docopt` when its not that complicated.

I wouldn't be against adding click, I'm open to changing to click and restructuring configuration [here](https://github.com/seanbreckenridge/keepassxc-pwned/blob/master/keepassxc_pwned/keepassxc_pwned.py#L39-L53) as version 0.3

**Comment by opensource-assist** [comment]
@seanbreckenridge
> Yeah, I've used click in the past.
> 
> I didn't expect the argument count to grow to what it is now, I tend to use `argparse`/`docopt` when its not that complicated.
> seanbreckenridge
> I wouldn't be against adding click, I'm open to changing to click and restructuring configuration [here](https://github.com/seanbreckenridge/keepassxc-pwned/blob/master/keepassxc_pwned/keepassxc_pwned.py#L39-L53) as version 0.3

This tool may grow to become much larger in the future; click is a high-level library which makes your life easier.
If you don't have the time, I can rewrite the tool and do the PR.

**Comment by purarue** [comment]
I can look into doing in later today, would make tests easier to write as well.

**Comment by purarue** [comment]
Pushed [current changes](https://github.com/seanbreckenridge/keepassxc-pwned/pull/11/files) to v0.3, still have some things to clean up

**Comment by purarue** [comment]
added in v0.3, which is merged into master/on pypi.
